### ISSUE TITLE
Issue with dissocing against gen data of 100

### ISSUE THREAD

**Issue by hughfdjackson** [hughfdjackson/persistent-hash-trie#15]
To Reproduce:
- Set the length of genned data to 100
- run tests

Expected:
- tests to pass, as they do for 10000

Actual:

```

> persistent-hash-trie@0.2.4 test /Users/hughfdjackson/r/personal/persistent-hash-trie
> mocha

TESTING SEED: 0.0875796212349087

  ․․․․․․․․․․․․․․․․․․․․․

  ✖ 1 of 21 tests failed:

  1) using random data assoc/dissoc/has/get on trie w/ 10000 items from depth 4 should allow us to dissoc first 10 keys:
     TypeError: Cannot read property 'type' of undefined
      at Object.dissoc (/Users/hughfdjackson/r/personal/persistent-hash-trie/src/persistent-hash-trie.js:275:26)
      ──────────────────────────────────────────────────────────────────────────────────────────────────────────
      273 » // Trie.
      274 » var dissoc = function(node, key, opts, depth){
      275 »     return dissocFns[node.type](node, key, opts || defaultOpts, depth || 0)
      ••••••••••••••••••••••••••••••••
      276 » }
      277 »
      278 » var dissocFns = {

      at /Users/hughfdjackson/r/personal/persistent-hash-trie/test/random-data-test.js:147:26
      ───────────────────────────────────────────────────────────────────────────────────────
      145 »
      146 »             var t = _.reduce(keys, function(trie, key){
      147 »                 return p.dissoc(trie, key, null, 4)
      ••••••••••••••••••••••••••••••••
      148 »             }, trie)
      149 »
      150 »             _.each(keys, function(prop){

      at Function.reduce (/Users/hughfdjackson/r/personal/persistent-hash-trie/node_modules/lodash/dist/lodash.js:2680:23)
      at Context.<anonymous> (/Users/hughfdjackson/r/personal/persistent-hash-trie/test/random-data-test.js:146:23)
      ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
      144 »         it('should allow us to dissoc first 10 keys', function(){
      145 »
      146 »             var t = _.reduce(keys, function(trie, key){
      •••••••••••••••••••••••••••••
      147 »                 return p.dissoc(trie, key, null, 4)
      148 »             }, trie)
      149 »

      at Test.run (/Users/hughfdjackson/r/personal/persistent-hash-trie/node_modules/mocha/lib/runnable.js:213:32)
      at Runner.runTest (/Users/hughfdjackson/r/personal/persistent-hash-trie/node_modules/mocha/lib/runner.js:343:10)
      at /Users/hughfdjackson/r/personal/persistent-hash-trie/node_modules/mocha/lib/runner.js:389:12
      at next (/Users/hughfdjackson/r/personal/persistent-hash-trie/node_modules/mocha/lib/runner.js:269:14)
      at /Users/hughfdjackson/r/personal/persistent-hash-trie/node_modules/mocha/lib/runner.js:278:7
      at next (/Users/hughfdjackson/r/personal/persistent-hash-trie/node_modules/mocha/lib/runner.js:226:23)
      at /Users/hughfdjackson/r/personal/persistent-hash-trie/node_modules/mocha/lib/runner.js:246:5
      at process._tickCallback (node.js:244:9)


npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by hughfdjackson** [comment]
Resolved in 58bb107a82093a37442c9bb2a0ac973197aede3b
